#!/bin/sh

echo "-----Normalizing other UFOs..."
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Idiqlat-Regular.ufo       &
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Idiqlat-ExtraLight.ufo       &
wait

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none --header sort_final,sort_final --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo 

# commented out and only to be used as a manual one-off process in case there is a build problem because of discrepancies with the orders
# psfremovegliflibkeys source/masters/Idiqlat-Regular.ufo com.schriftgestaltung.Glyphs.shapeOrder
# psfremovegliflibkeys source/masters/Idiqlat-ExtraLight.ufo com.schriftgestaltung.Glyphs.shapeOrder

echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -p scrlevel=w source/IdiqlatTestA.designspace 

echo "Building internal fea..."
makefea -o source/masters/Idiqlat-Regular.ufo/features.fea --ignoreglyphs -l source/logs/Idiqlat-Regular-makefea.log -i source/opentype/main.feax --omitaps "R, O, L" source/masters/Idiqlat-Regular.ufo &
makefea -o source/masters/Idiqlat-ExtraLight.ufo/features.fea  --ignoreglyphs -l source/logs/Idiqlat-Regular-makefea.log -i source/opentype/main.feax --omitaps "R, O, L" source/masters/Idiqlat-ExtraLight.ufo    &

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n  Idiqlat    -i org.sil.fonts -o source/Idiqlat-WOFF-metadata.xml source/masters/*-Regular.ufo  

wait

echo "-----Preflight completed!"
